trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Installation
    displayName: "Install Node.js and dependencies"
    jobs:
      - job: InstallNodeAndDependencies
        displayName: "Install Node.js and dependencies"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.9.0"
            displayName: "Install Node.js"

          - script: |
              npm install -g @angular/cli
              npm install
            displayName: "Install npm packages"

  - stage: Build
    displayName: "Build"
    jobs:
      - job: BuildAngularApp
        displayName: "Build Angular application"
        steps:
          - script: |
              npm run build:prod
            displayName: "Build Angular application"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "dist"
              ArtifactName: "drop"
              publishLocation: "Container"
            displayName: "Publish Artifact"

      - job: StandaloneJob
        displayName: "Standalone Job"
        steps:
          - script: echo "This is a standalone job"
            displayName: "Standalone Job Step"