trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Build and Deploy"
    jobs:
      - job: BuildAndDeploy
        displayName: "Build and Deploy"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.9.0"
            displayName: "Install Node.js"

          - script: |
              npm install -g @angular/cli
              npm install
            displayName: "Install npm packages"

          - script: |
              npm run build:prod
            displayName: "Build application"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "dist"
              ArtifactName: "drop"
              publishLocation: "Container"
            displayName: "Publish Artifact"
